// <auto-generated />
using System;
using DevOpsProject.Bms.Logic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevOpsProject.Bms.Logic.Migration
{
    [DbContext(typeof(BmsDbContext))]
    [Migration("20251124134253_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevOpsProject.Shared.Models.Entities.EwZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EwZones");
                });

            modelBuilder.Entity("DevOpsProject.Shared.Models.Entities.EwZoneHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("EwZoneHistory");
                });

            modelBuilder.Entity("DevOpsProject.Shared.Models.Entities.HiveRepositionSuggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherHiveId")
                        .HasColumnType("text");

                    b.Property<float>("OtherLatitude")
                        .HasColumnType("real");

                    b.Property<float>("OtherLongitude")
                        .HasColumnType("real");

                    b.Property<string>("SourceHiveId")
                        .HasColumnType("text");

                    b.Property<float>("SourceLatitude")
                        .HasColumnType("real");

                    b.Property<float>("SourceLongitude")
                        .HasColumnType("real");

                    b.Property<DateTime>("SuggestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceHiveId", "OtherHiveId", "IsConsumed");

                    b.ToTable("HiveRepositionSuggestions");
                });

            modelBuilder.Entity("DevOpsProject.Shared.Models.Entities.TelemetryHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("HiveId")
                        .HasColumnType("text");

                    b.Property<bool>("IsInEwZone")
                        .HasColumnType("boolean");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HiveId", "TimestampUtc");

                    b.ToTable("TelemetryHistory");
                });

            modelBuilder.Entity("DevOpsProject.Shared.Models.HiveStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("HiveId")
                        .HasColumnType("text");

                    b.Property<bool>("IsInEwZone")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTelemetryTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HiveId")
                        .IsUnique();

                    b.ToTable("HiveStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
